---
- hosts: jenkins-server
  become: true
  tasks:
    - name : Download Java 1.8 
      yum:
        name: java-1.8.0-openjdk-devel
        state: present

    # - name : Untar JDK
    #   unarchive:
    #     remote_src: yes
    #     src: /home/vagrant/openjdk-12.0.1_linux-x64_bin.tar.gz
    #     dest: /opt/
    
    - name: Copy java.sh
      template:
        src: java.j2
        dest: /etc/profile.d/java.sh
        owner: root
        group: root
    
    # - name: Source java
    #   shell: "source /etc/profile"
     
    - name: Ensure Jenkins Repository is Installed
      yum_repository:
        name: jenkins
        state: present
        description: Official Jenkins Yum Repo
        baseurl: http://pkg.jenkins.io/redhat/
        gpgkey: https://jenkins-ci.org/redhat/jenkins-ci.org.key
        gpgcheck: yes
        enabled: yes
    - name: Ensure Jenkins is Installed
      yum :
        name: jenkins
        update_cache: yes
        state: present

    # - name: Copy jenkins
    #   template:
    #     src: jenkins.j2
    #     dest: /etc/init.d/jenkins
    #     owner: root
    #     group: root
    # - name: Source jenkins
    #   shell: "source /etc/init.d/jenkins"
    - name : Reboot
      reboot:

    - name: Enable and Start the Jenkins Service
      service:
        name: jenkins
        enabled: yes
        state: started
    # - name: Open Firewall Port
    #   firewalld:
    #     zone: public
    #     port: 8080/tcp
    #     permanent: true
    #     state: enabled
    #     immediate: true
